### tokenize

In [2]:
import nltk

In [3]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [4]:
txt="NLtk provide powerfull tool for tokenize,it include word and sentence tokenizr"

In [5]:
txt

'NLtk provide powerfull tool for tokenize,it include word and sentence tokenizr'

In [6]:
type(txt)

str

In [7]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\omraj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [8]:
word_tokenize(txt)

['NLtk',
 'provide',
 'powerfull',
 'tool',
 'for',
 'tokenize',
 ',',
 'it',
 'include',
 'word',
 'and',
 'sentence',
 'tokenizr']

In [9]:
sent_tokenize(txt)

['NLtk provide powerfull tool for tokenize,it include word and sentence tokenizr']

### Stop Words Removal

In [12]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [13]:
sentence="this is a sample sentence, showing of the stop words filterization"

In [14]:
words=word_tokenize(sentence)

words

In [17]:
tokens=word_tokenize(sentence.lower())

In [19]:
new_senetence=[word for word in tokens if word in stopwords.words('english')]

In [21]:
new_senetence

['this', 'is', 'a', 'of', 'the']

In [22]:
new_senetence=[word for word in tokens if word not in stopwords.words('english')]

In [23]:
new_senetence

['sample', 'sentence', ',', 'showing', 'stop', 'words', 'filterization']

### Stemming VS Lemmatization

In [32]:
import nltk
from nltk.stem import PorterStemmer

stemmer=PorterStemmer()

In [54]:
words=['running','run','runner','happines','programming','bigger']

In [46]:
stemmer_words=[stemmer.stem(word) for word in words]

In [47]:
print(stemmer_words)

['run', 'run', 'runner', 'happin', 'program', 'bigger']

In [48]:
import nltk
from nltk.stem import WordNetLemmatizer

In [58]:
lemmatizer=WordNetLemmatizer()

In [61]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\omraj\AppData\Roaming\nltk_data...

True

In [62]:
lemmatizer_words=[lemmatizer.lemmatize(word) for word in words]

In [63]:
lemmatizer_words

['running', 'run', 'runner', 'happines', 'programming', 'bigger']

### Bag of Words

In [64]:
import numpy as np
import pandas as pd
from  sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [65]:
df=pd.read_csv("emails.csv")
df

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [66]:
len(df)

5172

In [69]:
df['category'].value_counts()

category
0    5142
1      18
2       8
6       2
4       1
3       1
Name: count, dtype: int64

In [70]:
df.head(5)

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

### Train  test spilt

In [78]:
x_train,x_test,y_train,y_test=train_test_split(df.the,df.to,test_size=0.2)

In [79]:
len(x_test)

1035

In [80]:
x_train[:4]

572     16
4519     6
3789     0
744      0
Name: the, dtype: int64

#### Create bag of words representeion using CountVectorize

In [82]:
v=CountVectorizer()

In [87]:
print(x_train.head())
print(type(x_train.iloc[0]))

572     16
4519     6
3789     0
744      0
1597     0
Name: the, dtype: int64
<class 'numpy.int64'>

In [88]:
print(x_train.head())

572     16
4519     6
3789     0
744      0
1597     0
Name: the, dtype: int64